# -*- coding: utf-8 -*-
"""Coursework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BN9OAJrjZqSvE74xMhynkn2qiamJHlME

# **F528328**
"""

with open('Board_Game_Info.txt', 'w') as f:#creates board game file
    f.write('GameID|Title|Genre|MinPlayers|MaxPlayers|PurchaseDate\n')
gameID=["mon01","scr12","che23","cas34","lud45","clu56","art67","chk78","jun89","uno90"]
title = ['Monopoly','Scrabble','Chess','Cashflow','Cludeo','Articulate','Checkers','Jungle Speed','Uno','Trivial Pursuit']
genre = ['Economic','Word','Strategy','Economic','Mystery','Word','Strategy','Card Game','Card Game','Strategy']
min_players = [2,2,2,2,2,4,2,2,2,2]
max_players = [6,4,2,4,4,20,2,6,6,5]
purchase_date = ['03-05-2025','12-09-2025','07-06-2025','24-01-2025','15-11-2025','01-04-2025','30-06-2025','21-12-2025','18-05-2025','27-03-2025']


with open('Board_Game_Info.txt', 'a') as f:#appends the board game file and adds the contents in it
  for i in range(len(gameID)):
        f.write(
            f"{gameID[i]}|{title[i]}|{genre[i]}|{min_players[i]}|{max_players[i]}|{purchase_date[i]}\n")

with open('Video_Game_Info.txt', 'w') as f:#creates video game file
    f.write('GameID|Title|Genre|Platform|PurchaseDate\n')
print("Video_Game_Info.txt")

gameID=["mk109","for98","ove87","gta76","min65","eaf54","rob43","day32","rus21","cla10"]
title = ['Mortal Kombat 1','Fortnite','Overwatch','GTA V','Minecraft','EA FC 26','Roblox','DayZ','Rust','ClashRoyale']
genre = ['Action','Action','Action','RPG','Survival','Sport','RPG','Survival','Survival','Strategy']
platform = ['Xbox','PC','Xbox','PS4','PS4','Xbox','PS4','PC','PC','Mobile']
purchase_date = ['12-06-2025','18-02-2025','01-12-2025','31-01-2025','21-04-2025','28-09-2025','04-011-2025','05-07-2025','11-07-2025','20-10-2025']


with open('Video_Game_Info.txt', 'a') as f:#appends the video game file and adds the contents in it
  for i in range(len(gameID)):
        f.write(
            f"{gameID[i]}|{title[i]}|{genre[i]}|{platform[i]}|{purchase_date[i]}\n")

"""it wont let me access any .pyc files so i am going to work around it"""

with open('Rental.txt', 'w') as f:#creates the rental file
    f.write('GameID|CustomerID|RentalDate|ReturnDate|Status\n')
#created random data
gameID = ["mon01","gta76","che23","day32","uno90","scr12","rob43","art67","cla10","min65",
        "cas34","rus21","lud45","chk78","ove87","clu56","eaf54","mk109","for98","jun89",
        "mon01","day32","che23","rob43","uno90","gta76","art67","cla10","min65","scr12",
        "jun89","cas34","rus21","lud45","for98","chk78","ove87","clu56","eaf54","mk109",
        "day32","rob43","mon01","uno90","che23","cla10","min65","art67","chk78","for98"]
customerID=[ "QXMD","LPTA","NHRK","ZVSC","BJFY","TUGW","KXEN","RCPA","MZHL","VDQJ",
    "SNYT","HGBK","WQFR","JXUP","CAVL","PRNE","DKTZ","YHSM","FQBA","XTRM",
    "VJLC","NZQP","GHTW","SCKN","LZVR","PBXH","TRQY","AMKD","JNVH","KPRT",
    "XGLS","WZNA","QHVC","DMRJ","YTPK","SVQX","BNTL","HZXF","RCWG","NQJD",
    "TLVM","KSGR","PVNY","XHQT","MCRZ","DJWP","ZKLA","FYHN","RWXT","QNLS"]
rental_date = ["2025-01-03","2025-01-04","2025-01-05","2025-01-06","2025-01-07",
    "2025-01-08","2025-01-09","2025-01-10","2025-01-11","2025-01-12",
    "2025-01-13","2025-01-14","2025-01-15","2025-01-16","2025-01-17",
    "2025-01-18","2025-01-19","2025-01-20","2025-01-21","2025-01-22",
    "2025-01-23","2025-01-24","2025-01-25","2025-01-26","2025-01-27",
    "2025-01-28","2025-01-29","2025-01-30","2025-01-31","2025-02-01",
    "2025-02-02","2025-02-03","2025-02-04","2025-02-05","2025-02-06",
    "2025-02-07","2025-02-08","2025-02-09","2025-02-10","2025-02-11",
    "2025-02-12","2025-02-13","2025-02-14","2025-02-15","2025-02-16",
    "2025-02-17","2025-02-18","2025-02-19","2025-02-20","2025-02-21"]
return_date = ["2025-01-07","2025-01-10","2025-01-08","2025-01-13","2025-01-12",
    "2025-01-15","2025-01-11","2025-01-17","2025-01-16","2025-01-20",
    "2025-01-18","2025-01-22","2025-01-19","2025-01-25","2025-01-23",
    "2025-01-27","2025-01-24","2025-01-29","2025-01-28","2025-02-01",
    "2025-01-30","2025-02-03","2025-02-02","2025-02-06","2025-02-04",
    "2025-02-08","2025-02-07","2025-02-10","2025-02-09","2025-02-12",
    "2025-02-13","2025-02-15","2025-02-16","2025-02-18","2025-02-17",
    "2025-02-20","2025-02-21","2025-02-23","2025-02-24","2025-02-25",
    "2025-02-26","2025-02-27","2025-02-28","2025-03-01","2025-03-02",
    "2025-03-03","2025-03-04","2025-03-05","2025-03-06","2025-03-07"]
status = [
    "returned", "not returned", "returned", "returned", "not returned",
    "returned", "not returned", "not returned", "returned", "not returned",
    "returned", "returned", "not returned", "returned", "not returned",
    "returned", "returned", "not returned", "not returned", "returned",
    "returned", "not returned", "returned", "not returned", "returned",
    "not returned", "returned", "returned", "not returned", "returned",
    "not returned", "not returned", "returned", "returned", "not returned",
    "returned", "returned", "not returned", "returned", "not returned",
    "returned", "not returned", "returned", "returned", "not returned",
    "returned", "not returned", "returned", "not returned", "returned"]
with open('Rental.txt', 'a') as f:#appends the rental file to add the contents
  for i in range(len(customerID)):
        f.write(f"{gameID[i]}|{customerID[i]}|{rental_date[i]}|{return_date[i]}|{status[i]}\n")

with open('Booking.txt', 'w') as f:
    f.write('CustomerID|BookingDate|Time|NumberOfGuests\n')
    #created random data
customerID = ["QXMD","LPTA","NHRK","ZVSC","BJFY","TUGW","KXEN","RCPA","MZHL","VDQJ",
    "SNYT","HGBK","WQFR","JXUP","CAVL","PRNE","DKTZ","YHSM","FQBA","XTRM",
    "VJLC","NZQP","GHTW","SCKN","LZVR","PBXH","TRQY","AMKD","JNVH","KPRT",
    "XGLS","WZNA","QHVC","DMRJ","YTPK","SVQX","BNTL","HZXF","RCWG","NQJD",
    "TLVM","KSGR","PVNY","XHQT","MCRZ","DJWP","ZKLA","FYHN","RWXT","QNLS"]
booking_date = ["2024-11-05","2024-11-07","2024-11-09","2024-11-12","2024-11-15",
    "2024-11-18","2024-11-21","2024-11-24","2024-11-27","2024-11-30",
    "2024-12-02","2024-12-04","2024-12-06","2024-12-09","2024-12-11",
    "2024-12-13","2024-12-16","2024-12-18","2024-12-20","2024-12-23",
    "2024-12-26","2024-12-28","2024-12-30","2025-01-02","2025-01-04",
    "2025-01-06","2025-01-08","2025-01-11","2025-01-13","2025-01-15",
    "2025-01-17","2025-01-20","2025-01-22","2025-01-24","2025-01-26",
    "2025-01-29","2025-01-31","2025-02-02","2025-02-05","2025-02-07",
    "2025-02-09","2025-02-12","2025-02-14","2025-02-16","2025-02-18",
    "2025-02-21","2025-02-23","2025-02-25","2025-02-27","2025-03-01"]
time = time_slots = [
    "2pm-6pm","6pm-10pm","2pm-6pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm","6pm-10pm","2pm-6pm","6pm-10pm",
    "2pm-6pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm",
    "6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm",
    "2pm-6pm","2pm-6pm","6pm-10pm","6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","2pm-6pm","6pm-10pm","2pm-6pm",
    "6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm","6pm-10pm","2pm-6pm","6pm-10pm","2pm-6pm","6pm-10pm"]

number_of_guests = [4, 2, 6, 1, 5, 3, 2, 6, 4, 1,
    3, 5, 6, 2, 4, 1, 5, 3, 6, 2,
    1, 4, 5, 3, 6, 2, 4, 1, 5, 3,
    6, 2, 4, 1, 5, 3, 2, 6, 4, 1,
    5, 3, 6, 2, 4, 1, 5, 3, 6, 2]
with open('Booking.txt', 'a') as f:
  for i in range(len(customerID)):
        f.write(
            f"{customerID[i]}|{booking_date[i]}|{time[i]}|{number_of_guests[i]}|\n")

with open('Feedback.txt', 'w') as f:
  f.write('CustomerID|GameReturned|DateReturned|Feedback\n')
#created random data
returnedCustomerID = ["QXMD","NHRK","ZVSC","TUGW","MZHL","SNYT","HGBK","JXUP","PRNE","DKTZ",
    "XTRM","VJLC","GHTW","LZVR","TRQY","AMKD","KPRT","QHVC","DMRJ","SVQX",
    "BNTL","RCWG","TLVM","PVNY","XHQT","DJWP","FYHN","QNLS"]

gameReturned = ["mon01","che23","day32","scr12","cla10","cas34","rus21","chk78","clu56","eaf54",
    "jun89","mon01","che23","uno90","art67","cla10","scr12","rus21","lud45","chk78",
    "ove87","eaf54","day32","mon01","uno90","cla10","art67","for98"]

returnDate = ["2025-01-07","2025-01-08","2025-01-13","2025-01-15","2025-01-16","2025-01-18","2025-01-22","2025-01-25","2025-01-27","2025-01-24",
    "2025-02-01","2025-01-30","2025-02-02","2025-02-04","2025-02-07","2025-02-10","2025-02-12","2025-02-16","2025-02-18","2025-02-20",
    "2025-02-21","2025-02-24","2025-02-26","2025-02-28","2025-03-01","2025-03-03","2025-03-05","2025-03-07"]
feedBack = ["Amazing","Fun","Challenging","Classic","Addictive","Strategic","Hilarious","Engaging","Smooth","Competitive",
    "Simple","Brilliant","Entertaining","Tense","Satisfying","Enjoyable","Balanced","Quick","Impressive","Memorable",
    "Fantastic","Solid","Creative","Relaxing","Intense","Clever","Pleasant","Recommended"]
with open('Feedback.txt', 'a') as f:

  for i in range(len(returnedCustomerID)):
        f.write(
            f"{returnedCustomerID[i]}|{gameReturned[i]}|{returnDate[i]}|{feedBack[i]}|\n")



"""### **Board Game**"""

import ipywidgets as widgets
from IPython.display import display, clear_output


def sepRow(line):#separates the columns in teh txt file with a '|' and removes extra spacing
  line = line.strip()
  if line == "":
    return []
  if "|" in line:
    stuff = line.split("|")
    newstuff = []
    for i in range(len(stuff)):
      bit = stuff[i].strip()
      newstuff.append(bit)
    return newstuff
  return line.split()

def loadBgames(filename):#returns a list of dictionaries from the board game txt for each game
  games= []
  try:
    file = open(filename, "r")
  except:
    return games

  firstline = file.readline()#skips header
  for line in file:
    line = line.strip()
    row = line.split("|")

    if len(row) < 6:
      continue
    g =row[0].strip()#uses 0 base indexing to allow me to access each column easier
    t =row[1].strip()
    gen =row[2].strip()
    minp =row[3].strip()
    maxp =row[4].strip()
    d =row[5].strip()

    if minp==maxp:
      play =minp
    else:
      play =minp + "-" + maxp
    oneGame ={}
    oneGame["id"] =g
    oneGame["name"] =t
    oneGame["genre"] =gen
    oneGame["players"] =play
    oneGame["date"] =d

    games.append(oneGame)
  file.close()
  return games
def returned_rental_info(filename):#looks at the rental txt to see the status
  allinfo ={}

  try:
    f= open(filename, "r")
  except:
    return allinfo

  f.readline()

  for line in f:
    bits =sepRow(line)

    if len(bits) < 2:
      continue

    gameid =bits[0].strip().lower()

    s = ""
    d = ""

    if len(bits) >=5:
      s = bits[4].strip().lower()
    if len(bits) >=4:
      d = bits[3].strip()

    result ={}
    result["status"] =s
    result["return_date"] =d

    allinfo[gameid] =result

  f.close()
  return allinfo


def gameAvailable(rInfo, gameID):#if game has been returned then it is available
  gid = gameID.strip().lower()

  if gid not in rInfo:
    return True

  info= rInfo[gid]
  st =info["status"]
  rd =info["return_date"]

  if st=="not returned":
    return False
  if st=="returned":
    return True
  if rd=="":
    return False

  return True


def runBSearch(button):#if they search for board games then it filters the games to match what they want
  with button.outBox:
    clear_output()

    typed =button.keyBox.value
    typed =typed.strip()
    typed =typed.lower()

    how = button.modeDrop.value

    if typed == "":
      print("type something first")
      return

    allGames = loadBgames(button.boardFile)

    if allGames==[]:
      print("No games loaded (check Board_Game_Info.txt)")
      return

    rentalInfo = returned_rental_info(button.rentalFile)

    results =[]

    for i in range(len(allGames)):
      g = allGames[i]
# this adds games to g is the what they filtered matches
      if how=="ID":
        gid = g["id"].strip().lower()
        if typed in gid:
          results.append(g)
      elif how=="Title":
        title =g["name"].strip().lower()
        if typed in title:
          results.append(g)
      else:
        genre =g["genre"].strip().lower()
        if typed in genre:
          results.append(g)

    if results == []:
      print("No matching games found")
      return

    print("Matches:")
    for j in range(len(results)):
      g = results[j]

      avail = gameAvailable(rentalInfo, g["id"])
      if avail==True:
        stat ="Available"
      else:
        stat ="Not Available"

      print(g["id"], "-", g["name"])
      print("genre:", g["genre"], "players:", g["players"])
      print("date:", g["date"], "status:", stat)
      print("")


def pressSearch(button):#if they do press the search button they it runs the function above
    runBSearch(button)


def enterPressed(textbox):#it also runs the function above when the enter button is pressed
    if textbox.searchbutton != None:
        runBSearch(textbox.searchbutton)


def buildBoard_search_widget(board_file="Board_Game_Info.txt", rental_file="Rental.txt"):#this is what displays and creates the widgets
    outBox = widgets.Output()

    modeDrop = widgets.Dropdown(#drops to select if they want a title or genre
        options=["ID", "Title", "Genre"],
        value="Title",
        description="Search:"
    )

    keyBox = widgets.Text(
        description="Key:",
        placeholder="e.g. mon01 / monopoly / strategy"#a placeholder gives the user an idea of what to type
    )

    b = widgets.Button(description="Search")

    b.boardFile = board_file
    b.rentalFile = rental_file
    b.outBox = outBox
    b.modeDrop = modeDrop
    b.keyBox = keyBox

    keyBox.searchbutton = b

    b.on_click(pressSearch)
    keyBox.on_submit(enterPressed)

    ui = widgets.VBox([ #building the layout as a vertical stack
        widgets.HTML("<h3>Board Game Search</h3>"),
        widgets.HBox([modeDrop, keyBox, b]),
        outBox
    ])
    return ui

"""## **Video Game**"""

def checkRent(file, idIn, gameIn):#function that searches rental txt to removes extra spacing and keep it lowercase
    idIn = idIn.strip().lower()
    gameIn = gameIn.strip().lower()

    if idIn == '' or gameIn == '':#ensures both inputs were typed in
        return "Please enter both Customer ID and Game ID."

    f = open(file, "r")#opens rental file and separates the columns with '|'
    f.readline()
    for line in f:
        stuff = line.strip().split("|")
        if len(stuff) < 5:
            continue
        g = stuff[0].strip().lower()#using 0 base indexing to get the gameId and customerId
        c = stuff[1].strip().lower()
        if g != gameIn or c != idIn:
            continue
        stat = stuff[4].strip()
        f.close()
        return "Match found:\nCustomer ID: " + c.upper() + "\nGame ID: " + g + "\nStatus: " + stat
    f.close()#close file if there are no matches
    return "No matches found."

def clickIt(b):#function to rent search and print result to the output widget
    with b.out:
        clear_output()
        r = checkRent(b.file, b.idBox.value, b.gameBox.value)
        print(r)

def readVideoGames(filename):#reads video game txt games as dictionaries
  games = []
  f = open(filename,"r")
  f.readline()

  for line in f:
    parts = line.strip().split("|")
    if len(parts) < 5:
      continue
    one = {}
    one["id"] = parts[0].strip()#stores all of it
    one["title"] = parts[1].strip()
    one["genre"] = parts[2].strip()
    one["platform"] = parts[3].strip()
    one["purchase"] = parts[4].strip()

    games.append(one)#adds it to the empty list

  f.close()
  return games


def doVideoSearch(button):#if user clicks esearch on the video games it will print the widget output and clears previous output
    with button.out:
        clear_output()

        key = button.term.value.strip().lower()
        if key == "":#chekcs if they have typed something
            print("type something")
            return

        games = readVideoGames(button.file)
        field = "title" if button.mode.value == "Title" else "genre"#they can choose what to filter it by

        matches = []
        for g in games:
            if key in g[field].lower():
                matches.append(g)#adds all the mathcing games to the empty set

        if matches == []:#empty set, so nothing mathces therefore no matching games found
            print("No matching games found")
            return

        print("Matching video games:")#prints headings
        for g in matches:
            print(g["id"], "|", g["title"], "|", g["genre"], "|", g["platform"], "|", g["purchase"])


def enterVideoPressed(textbox):#calls function if user presses enter
    doVideoSearch(textbox.searchBtn)


def buildVideo_search_widget(file="Video_Game_Info.txt"):#builds all the video game widgets
    out = widgets.Output()
    mode = widgets.Dropdown(options=["Title", "Genre"], value="Title", description="Search:")#dropdown choices to make it easier for user
    term = widgets.Text(description="Key:", placeholder="e.g. minecraft / survival")
    button = widgets.Button(description="Search")
#stores everything
    button.out = out
    button.mode = mode
    button.term = term
    button.file = file

    term.searchBtn = button

    button.on_click(doVideoSearch)
    term.on_submit(enterVideoPressed)

    return widgets.VBox([#builds the layout as a vertical stack
        widgets.HTML("<h3>Video Game Search</h3>"),
        widgets.HBox([mode, term, button]),
        out
    ])

"""## **Game Rent**"""

def searchRent(f, cid, gid):#looks at rental files to removes spaces and making everything lowercase
    cid = cid.strip().lower()
    gid = gid.strip().lower()

    if cid=='' or gid=='':#makes sure user types both
        return "Need both fields."

    file =open(f, "r")#reads rental txt and separates the columns with '|'
    _ =file.readline()
    for l in file:
        x =l.strip().split("|")
        if len(x) < 5:
            continue
        a =x[0].strip().lower()#0 bases indexing to get gameid and customerid
        b = x[1].strip().lower()
        if b !=cid or a !=gid:#this checks that both ids are in one row and if it doesn't it moves to the next row
            continue
        s =x[4].strip()#gets the status of the game
        file.close()
        return "Match found:\nCustomer ID: " + b.upper() + "\nGame ID: " + a + "\nStatus: " + s#returns the resulsts
    file.close()

    return "No match."#but if nothing matches, it returns nothign

def clicker(b):#if the rent button is clicked the it prints out the widget and clears previous output
    with b.o:
        clear_output()
        res =searchRent(b.f, b.c.value, b.g.value)#calls the searchrent function and prints resultant message
        print(res)

def buildGameRentWidget(fp="Rental.txt"):#builds the actual widget
    c = widgets.Text(description="CustomerID:",placeholder = "qxmd")#placeholders to give them an idea of what to time
    g = widgets.Text(description="Game:",placeholder="mon01")
    button = widgets.Button(description="Search Rented Games")
    o = widgets.Output()

    button.c = c
    button.g = g
    button.f = fp
    button.o = o
    button.on_click(clicker)#basically if they click the button the it goes back to the clicker function

    return widgets.VBox([widgets.HTML("<h3>Rental Check</h3>"), widgets.HBox([c, g, button]), o])#formats the output

"""## **GameReturn**"""

def buildGameReturnWidget(f="Feedback.txt"):#builds the widgets



  g = widgets.Text(description="Game ID:", placeholder="mon01")#creates the boxes
  b = widgets.Button(description="Search")
  o = widgets.Output()

  def click(e):#function is called when the search button is clicked and clears previous output
        with o:
          clear_output()
          game = g.value.strip().lower()#gameId is typed in

          if game == "":
             print("Type a game id")#if nothign is typed then they need to type something
             return

          f2 = open(f, "r")#this whole parts justs reads the rest of the lines
          f2.readline()
          lines = f2.readlines()
          f2.close()

          found = []#empty set to add the eventual matching rows

          for l in lines:#makes sure lines are separated and rows have 4 columns
                if "|" in l:
                   bits = l.strip().split("|")
                   if len(bits) > 3:
                        if bits[1].strip().lower() == game:
                             found.append(bits)#adds the matching sets to the empty set

          if found == []:#if no matching sets then nothign is founfd
               print("No feedback found")
               return

          for r in found:#prints everything out
              print("CustomerID:", r[0])
              print("Game:", r[1])
              print("DateReturned:", r[2])
              print("Feedback:", r[3])
              print("")

  b.on_click(click)#click function is called when they press on search --> this is what links them

  return widgets.VBox([#builds the layout of the ouptut
      widgets.HTML("<h3>Return Game (Find Feedback)</h3>"),
      widgets.HBox([g, b]),
      o
  ])

"""### **Booking Display**"""

def is_valid_customerID(cid):#checks if the customer id is written in the correct format
  if len(cid)!=4:#is 4 characters
      return False
  if cid.isalpha()==False:#is letters only
     return False
  return True


def is_valid_date(d):#checks the date aswell is in the correct format
  if len(d)!=10:
      return False
  if d[4]!="-" or d[7]!="-":#makes sure the dashes are in the right places
      return False

  y=d[0:4]#splicing to insert show year, month, day
  m=d[5:7]
  day=d[8:10]

  if not y.isdigit() or not m.isdigit() or not day.isdigit():#makes sure they are digits
      return False

  if int(m)<1 or int(m)>12:
      return False
  if int(day)<1 or int(day)>31:
      return False

  return True


def buildBooking_widget(file="Booking.txt"):#builds the actual widget

  out=widgets.Output()#all the widget boxes and waht they will show
  cid=widgets.Text(description="Customer:",placeholder="e.g. qxmd")
  d=widgets.Text(description="Date:",placeholder="YYYY-MM-DD")
  slot=widgets.Dropdown(options=["2pm","6pm"],description="Session:")
  g=widgets.Dropdown(options=[0,1,2,3],description="Guests:")
  button=widgets.Button(description="Book")

  def click(e):#when the book button is pressed it will run and clears previous output
        with out:
          clear_output()
          #collects all the inputs
          c=cid.value.strip().lower()
          date=d.value.strip()
          time=slot.value.strip().lower()
          guests=g.value

          if is_valid_customerID(c)==False:#make sure its valid
              print("Customer ID must be 4 letters")
              return

          if is_valid_date(date)==False:#makes sure date is valid
             print("Date must be YYYY-MM-DD")
             return

          if time!="2pm" and time!="6pm":#make sure only these 2 times are chosen but as im writing this i realise it wasn't needed
               print("Session must be 2pm or 6pm")
               return

          if str(guests).isdigit()==False:#makes the guests are a number
               print("Guests must be a number")
               return

          guests=int(guests)
          if guests<0 or guests>3: # and limits the amount of guest but also not needed
               print("Guests must be between 0 and 3")
               return

          count=0#stores people already booked
          f=open(file,"r")#checks capacity
          f.readline()
          for line in f:
              if "|" in line:
                   x=line.strip().split("|")
                   if len(x)==4:
                        if x[1]==date and x[2].lower()==time:
                             count=count+1+int(x[3])#adds the customer and guest
          f.close()

          if count+guests+1>50:#makes sure max 50 people
              print("That session is full")
              return

          f=open(file,"a")#saves the booking
          f.write(c+"|"+date+"|"+time+"|"+str(guests)+"\n")
          f.close()

          print("Booking confirmed")

  button.on_click(click)

  return widgets.VBox([#builds the layout of the outputs
     widgets.HTML("<h3>Booking System</h3>"),
     widgets.HBox([cid,d]),
     widgets.HBox([slot,g,button]),
     out
  ])



"""# **Display**"""

def showScreen(out_area, content):#function to clear the old output and display a new ui
    with out_area:
        clear_output()
        display(content)


def menuBoardSearchClicked(button):#runs the board game function when board games are pressed
    state = button._menu_state
    ui = buildBoard_search_widget(state["board_file"], state["rental_file"])#builds the screen for board game search
    showScreen(state["out_area"], ui)


def menuVideoSearchClicked(button):#runs the video game function when video games are pressed
    state = button._menu_state
    ui = buildVideo_search_widget(state["video_file"])
    showScreen(state["out_area"], ui)


def menu_search_clicked(button):#runs when users clicks on the search games button, it will output the widgets for board and video
    state = button._menu_state

    board_button = widgets.Button(description="Board Games")
    video_button = widgets.Button(description="Video Games")

    board_button._menu_state = state
    video_button._menu_state = state

    board_button.on_click(menuBoardSearchClicked)#pressed the board or video opens up their menu
    video_button.on_click(menuVideoSearchClicked)

    ui = widgets.VBox([#builds the layout for the search menu
        widgets.HTML("<h3>Search Games</h3>"),
        widgets.HBox([board_button, video_button])
    ])
    showScreen(state["out_area"], ui)


def menuBook_clicked(button):#runs when user pressed on book and the booking widgets are built
    state = button._menu_state
    ui = buildBooking_widget(state["booking_file"])
    showScreen(state["out_area"], ui)


def menu_rent_clicked(button):#same but with rent
    state = button._menu_state
    ui = buildGameRentWidget(state["rental_file"])
    showScreen(state["out_area"], ui)


def menu_return_clicked(button):#same but with return
    state = button._menu_state
    ui = buildGameReturnWidget(state["feedback_file"])
    showScreen(state["out_area"], ui)


def display_main_menu(#outputs the main menu and all the buttons
    board_file="Board_Game_Info.txt",
    video_file="Video_Game_Info.txt",
    rental_file="Rental.txt",
    booking_file="Booking.txt",
    feedback_file="Feedback.txt"):

    out_area = widgets.Output()

    searchButton = widgets.Button(description="Search Games")#creates the buttons on the main menu
    rentButton = widgets.Button(description="Rent Game")
    bookButton = widgets.Button(description="Book Session")
    returnButton = widgets.Button(description="Return Game")

    menu_state = {#shares the data to allow every menu button to use
        "out_area": out_area,
        "board_file": board_file,
        "video_file": video_file,
        "rental_file": rental_file,
        "booking_file": booking_file,
        "feedback_file": feedback_file}

    searchButton._menu_state = menu_state#personalised the shared data to themselves
    rentButton._menu_state = menu_state
    bookButton._menu_state = menu_state
    returnButton._menu_state = menu_state

    searchButton.on_click(menu_search_clicked)#menus open when you press on each of them
    rentButton.on_click(menu_rent_clicked)
    bookButton.on_click(menuBook_clicked)
    returnButton.on_click(menu_return_clicked)

    app = widgets.VBox([#creates the layout
        widgets.HBox([searchButton, rentButton, bookButton, returnButton]),
        out_area
    ])


    display(app)


display_main_menu()